version: "3"

services:
  kanboard:
    image: kanboard/kanboard
    volumes:
      - /share/appdata/kanboard/data:/var/www/app/data
      - /share/appdata/kanboard/plugins:/var/www/app/plugins
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:kanboard.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=80
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.8.0/24
