version: "3"

services:
  kanboard:
    image: kanboard/kanboard
    volumes:
      - /share/appdata/kanboard/data:/var/www/app/data
      - /share/appdata/kanboard/plugins:/var/www/app/plugins
    networks:
      - internal

  proxy:
    image: bitnami/oauth2-proxy:latest
    env_file: /share/appdata/config/kanboard/kanboard.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:kanboard.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /share/appdata/config/kanboard/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://kanboard
      -redirect-url=https://kanboard.example.com
      -http-address=http://0.0.0.0:4180
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.8.0/24
