version: "3.2"

services:
  diskover:
    image: linuxserver/diskover:latest
    env_file: /share/appdata/config/diskover/diskover.env
    volumes:
      - /share/appdata/diskover/config:/config
      - /share/Multimedia/Filme:/data/Filme
      - /share/Multimedia/Serien:/data/Serien
      - /share/appdata:/data/appdata
    # Or, you can bind multiple host directories under the /data directory for scanning.
    #- /share/Photos:/data/photos
    #- /share/downloads:/data/downloads
    #- /share/appdata:/data/appdata
    networks:
      - internal
      - traefik_public
    deploy:
      resources:
        limits:
          memory: 4096M
      labels:
        - traefik.disk.frontend.rule=Host:diskover.example.com
        - traefik.disk.port=80
        - traefik.docker.network=traefik_public
        - "traefik.disk.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.disk.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
        - traefik.dash.frontend.rule=Host:diskoverdash.example.com
        - traefik.dash.port=9181
        - "traefik.dash.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.dash.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  elasticsearch:
    image: elasticsearch:5.6-alpine
    volumes:
      - /share/appdata/runtime/diskover/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  redis:
    image: redis:alpine
    volumes:
      - /share/appdata/runtime/diskover/redis:/data
    networks:
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.48.0/24
