version: "3"

services:
  heimdall:
    image: linuxserver/heimdall:latest
    env_file: /share/appdata/config/autopirate/heimdall.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/appdata/autopirate/heimdall:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:heimdall.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=80
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  organizr:
    image: organizrtools/organizr-v2:latest
    env_file: /share/appdata/config/autopirate/organizr.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/appdata/autopirate/organizr:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:organizr.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=80
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  oscarr:
    image: morpheus65535/oscarr:latest
    env_file: /share/appdata/config/autopirate/oscarr.env
    volumes:
      - /share/appdata/autopirate/oscarr:/oscarr/data
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:oscarr.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=5656
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  #  bazarr:
  #    image: linuxserver/bazarr:latest
  #    env_file: /share/appdata/config/autopirate/bazarr.env
  #    volumes:
  #      - /share/appdata/autopirate/bazarr:/config
  #      - /share/Multimedia/Serien:/tv
  #      - /share/Multimedia/Filme:/movies
  #    networks:
  #      - internal
  #      - traefik_public
  #    deploy:
  #      labels:
  #        - traefik.frontend.rule=Host:bazarr.example.com
  #        - traefik.docker.network=traefik_public
  #        - traefik.port=6767
  #      - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
  #      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  #  sabnzbd:
  #    image: linuxserver/sabnzbd
  #    volumes:
  #      - /var/data/media/:/media
  #      - share/appdata/autopirate/sabnzbd:/config
  #    networks:
  #      - internal
  #      - traefik_public
  #    deploy:
  #      labels:
  #      - traefik.frontend.rule=Host:sabnzbd.example.com
  #      - traefik.docker.network=traefik_public
  #      - traefik.port=8080
  #      - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
  #      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  nzbget:
    image: linuxserver/nzbget:latest
    env_file: /share/appdata/config/autopirate/nzbget.env
    volumes:
      - /share/appdata/autopirate/nzbget:/config
      - /share/Multimedia/:/media
    networks:
      - internal
      - traefik_public
    ports:
      - 5075:5075
    deploy:
      labels:
        - traefik.frontend.rule=Host:nzbget.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=6789
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  #  rtorrent:
  #    image: linuxserver/rutorrent
  #    env_file: /share/appdata/config/autopirate/rtorrent.env
  #    ports:
  #      - 36898:36898
  #      - 3475:80
  #    volumes:
  #      - /var/data/media/:/media
  #      - /share/appdata/autopirate/rtorrent:/config
  #    networks:
  #      - internal
  #      - traefik_public
  #    deploy:
  #      labels:
  #      - traefik.frontend.rule=Host:rtorrent.maskpx.com
  #      - traefik.docker.network=traefik_public
  #      - traefik.port=80
  #      - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
  #      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    volumes:
      - /share/Multimedia/:/media
      - /share/appdata/autopirate/lazylibrarian:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:lazylibrarian.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=5299
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  #mylar:
  #  image: linuxserver/mylar:latest
  #  volumes:
  #    - /share/Multimedia/:/media
  #    - /share/appdata/autopirate/mylar:/config
  #  networks:
  #    - internal
  #    - traefik_public
  #  deploy:
  #    labels:
  #      - traefik.frontend.rule=Host:mylar.example.com
  #      - traefik.docker.network=traefik_public
  #      - traefik.port=8090
  #      - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
  #      - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  ombi:
    image: linuxserver/ombi:latest
    volumes:
      - /share/Multimedia/:/media
      - /share/appdata/autopirate/ombi:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:ombi.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=3579

  #headphones:
  #  image: linuxserver/headphones:latest
  #  volumes:
  #    - /var/data/media/:/media
  #    - /share/appdata/autopirate/headphones:/config
  #  networks:
  #    - internal
  #    - traefik_public
  #  deploy:
  #    labels:
  #    - traefik.frontend.rule=Host:headphones.example.com
  #    - traefik.docker.network=traefik_public
  #    - traefik.port=8181
  #    - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
  #    - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  radarr:
    image: linuxserver/radarr:latest
    env_file: /share/appdata/config/autopirate/radarr.env
    volumes:
      - /share/Multimedia/:/media
      - /share/appdata/autopirate/radarr:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:radarr.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=7878

  sonarr:
    image: linuxserver/sonarr:latest
    env_file: /share/appdata/config/autopirate/sonarr.env
    volumes:
      - /share/Multimedia/:/media
      - /share/appdata/autopirate/sonarr:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:sonarr.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=8989
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  lidarr:
    image: linuxserver/lidarr:latest
    env_file: /share/appdata/config/autopirate/lidarr.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Multimedia:/media
      - /share/appdata/autopirate/lidarr:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:lidarr.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=8686
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

  nzbhydra:
    image: linuxserver/hydra2:latest
    volumes:
      - /share/Multimedia/:/media
      - /share/appdata/autopirate/nzbhydra:/config
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:nzbhydra.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=5076
        - "traefik.frontend.auth.forward.address=http://192.168.200.2:8080/authorize"
        - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.11.0/24
