version: "3.0"

services:
  emby:
    image: emby/embyserver:latest
    env_file: /share/appdata/config/emby/emby.env
    volumes:
      - /share/appdata/emby:/config
      - /share/Multimedia/:/data
    networks:
      - traefik_public
      - internal
    ports:
      - 8096:8096

    deploy:
      labels:
        - traefik.frontend.rule=Host:emby.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=8096
        - traefik.frontend.passHostHeader=true

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.17.0/24
