checkNewVersion = true
 
defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true 
 
logLevel = "DEBUG"
 
# Set to log to file rather than (default STDOUT). Comment out to send to Graylog.
[traefikLog]
  filePath = "/etc/traefik/traefik.log"
 
#[accessLog]
#  filePath = "/path/to/access.log"
#
#  [accessLog.filters]
#    statusCodes = ["200", "300-302"]
#    retryAttempts = true
#    minDuration = "10ms"
 
[entryPoints]
  [entryPoints.http]
   address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["172.0.0.1/8"]	  
    [entryPoints.http.redirect]
      entryPoint = "https"
 [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
#    [[entryPoints.https.tls.certificates]]
#	  certFile = "/etc/traefik/ssl/example.crt"
#	  keyFile = "/etc/traefik/ssl/example.key"
#    [[entryPoints.https.tls.certificates]]
#	  certFile = "/etc/traefik/ssl/qnapunofficial.crt"
#	  keyFile = "/etc/traefik/ssl/qnapunofficial.key"
#    [[entryPoints.https.tls.certificates]]
#	  certFile = "/etc/traefik/ssl/oracleoptimizer.crt"
#	  keyFile = "/etc/traefik/ssl/oracleoptimizer.key"

	  
[retry]
 
[api]
  entrypoint = "traefik"
  dashboard = true
 
[docker]
  endpoint = "tcp://127.0.0.1:2375"
  domain = "example.com"
  watch = true
  exposedbydefault = false
  #swarmmode = true
 
[acme]
  email = "example@example.com"  
  storage = "/etc/traefik/acme.json"  
  entryPoint = "https"  
#  acmeLogging = true
  onHostRule = true
  #onDemand = true
#  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  #[acme.httpChallenge]
  #entryPoint = "http"
 
[acme.dnsChallenge]
  provider = "cloudflare"
#  delayBeforeCheck = 5
  resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
 
[[acme.domains]]
  main = "*.example.com"
  sans = ["example.com"]
 
[file]
  watch=true
  filename = "/etc/traefik/rules.toml"
 