version: "3.2"

services:
  app:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

  proxy:
    image: bitnami/oauth2-proxy:latest
    env_file: /share/appdata/config/dozzle/dozzle.env
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:logs.example.com
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /share/appdata/config/dozzle/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://app:8080
      -redirect-url=https://logs.example.com
      -http-address=http://0.0.0.0:4180
      -provider=github
      -authenticated-emails-file=/authenticated-emails.txt

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.48.0/24
